Fil-C changes to pcre2-10.48 since 7978954dbd2efc6f2196869290553cf1871b4ce6
Ports the pcre2-10.47 Fil-C changes (54bcb9611f15 and 1f0ce13bb2de) to
10.48. Nothing needed adapting: the bad-locale test is still Test 150
with the same locale.bad/shell-error structure, and the script callout
tests still emit --- Test N --- markers and RC lines over the same
eight pcre2grep invocations. Test 150's behavior under Fil-C differs
from what the expected output assumes, so it is skipped and the
expected output records SKIPPED. The script callout tests get
--line-buffered because, under highly specific system conditions,
output from pcre2grep's fwrites can be delayed past its calls to
/bin/echo, causing spurious test failures.

diff --git a/projects/pcre2-10.48/RunGrepTest b/projects/pcre2-10.48/RunGrepTest
--- a/projects/pcre2-10.48/RunGrepTest
+++ b/projects/pcre2-10.48/RunGrepTest
@@ -864,20 +864,21 @@ echo "RC=$?" >>testtrygrep
 # output matches.
 
 echo "---------------------------- Test 150 -----------------------------" >>testtrygrep
-which locale >/dev/null 2>&1
-if [ $? -ne 0 ]; then
-  echo "pcre2grep: Failed to set locale locale.bad (obtained from LC_CTYPE)" >>testtrygrep
-  echo "RC=2" >>testtrygrep
-else
-
-  (cd $srcdir; unset LC_ALL; LC_CTYPE=locale.bad; export LC_CTYPE; $valgrind $vjs $pcre2grep abc /dev/null >>$builddir/testtrygrep 2>&1) >testtemp1grep 2>&1
-  echo "RC=$?" >>testtrygrep
-  shell_errors=`cat testtemp1grep`
-  if [ x"$shell_errors" != x ] ; then
-    printf "shell errors during locale test: "
-    echo "$shell_errors"
-  fi
-fi
+echo "SKIPPED" >>testtrygrep
+# which locale >/dev/null 2>&1
+# if [ $? -ne 0 ]; then
+#   echo "pcre2grep: Failed to set locale locale.bad (obtained from LC_CTYPE)" >>testtrygrep
+#   echo "RC=2" >>testtrygrep
+# else
+#
+#   (cd $srcdir; unset LC_ALL; LC_CTYPE=locale.bad; export LC_CTYPE; $valgrind $vjs $pcre2grep abc /dev/null >>$builddir/testtrygrep 2>&1) >testtemp1grep 2>&1
+#   echo "RC=$?" >>testtrygrep
+#   shell_errors=`cat testtemp1grep`
+#   if [ x"$shell_errors" != x ] ; then
+#     printf "shell errors during locale test: "
+#     echo "$shell_errors"
+#   fi
+# fi
 
 echo "---------------------------- Test 151 -----------------------------" >>testtrygrep
 (cd $srcdir; $valgrind $vjs $pcre2grep --colour=always -e this -e The -e 'The wo' testdata/grepinputv) >>testtrygrep
@@ -1266,22 +1267,22 @@ fi
 if $valgrind $vjs $pcre2grep --help | $valgrind $vjs $pcre2grep -q 'callout scripts in patterns are supported'; then
   echo "Testing pcre2grep script callouts"
   echo "--- Test 1 ---" >testtrygrep
-  $valgrind $vjs $pcre2grep '(T)(..(.))(?C"/bin/echo|Arg1: [$1] [$2] [$3]|Arg2: $|${1}$| ($4) ($14) ($0)")()' $srcdir/testdata/grepinputv >>testtrygrep
+  $valgrind $vjs $pcre2grep --line-buffered '(T)(..(.))(?C"/bin/echo|Arg1: [$1] [$2] [$3]|Arg2: $|${1}$| ($4) ($14) ($0)")()' $srcdir/testdata/grepinputv >>testtrygrep
   echo "RC=$?" >>testtrygrep
   echo "--- Test 2 ---" >>testtrygrep
-  $valgrind $vjs $pcre2grep '(T)(..(.))()()()()()()()(..)(?C"/bin/echo|Arg1: [$11] [${11}]")' $srcdir/testdata/grepinputv >>testtrygrep
+  $valgrind $vjs $pcre2grep --line-buffered '(T)(..(.))()()()()()()()(..)(?C"/bin/echo|Arg1: [$11] [${11}]")' $srcdir/testdata/grepinputv >>testtrygrep
   echo "RC=$?" >>testtrygrep
   echo "--- Test 3 ---" >>testtrygrep
-  $valgrind $vjs $pcre2grep '(T)(?C"|$0:$1$n")' $srcdir/testdata/grepinputv >>testtrygrep
+  $valgrind $vjs $pcre2grep --line-buffered '(T)(?C"|$0:$1$n")' $srcdir/testdata/grepinputv >>testtrygrep
   echo "RC=$?" >>testtrygrep
   echo "--- Test 4 ---" >>testtrygrep
-  $valgrind $vjs $pcre2grep '(T)(?C"/bin/echo|$0:$1$n")' $srcdir/testdata/grepinputv >>testtrygrep
+  $valgrind $vjs $pcre2grep --line-buffered '(T)(?C"/bin/echo|$0:$1$n")' $srcdir/testdata/grepinputv >>testtrygrep
   echo "RC=$?" >>testtrygrep
   echo "--- Test 5 ---" >>testtrygrep
-  $valgrind $vjs $pcre2grep '(T)(?C"|$1$n")(*F)' $srcdir/testdata/grepinputv >>testtrygrep
+  $valgrind $vjs $pcre2grep --line-buffered '(T)(?C"|$1$n")(*F)' $srcdir/testdata/grepinputv >>testtrygrep
   echo "RC=$?" >>testtrygrep
   echo "--- Test 6 ---" >>testtrygrep
-  $valgrind $vjs $pcre2grep -m1 '(T)(?C"|$0:$1:$x{41}$o{101}$n")' $srcdir/testdata/grepinputv >>testtrygrep
+  $valgrind $vjs $pcre2grep --line-buffered -m1 '(T)(?C"|$0:$1:$x{41}$o{101}$n")' $srcdir/testdata/grepinputv >>testtrygrep
   echo "RC=$?" >>testtrygrep
 
   if $valgrind $vjs $pcre2grep --help | $valgrind $vjs $pcre2grep -q 'Non-fork callout scripts in patterns are supported'; then
@@ -1298,10 +1299,10 @@ if $valgrind $vjs $pcre2grep --help | $valgrind $vjs $pcre2grep -q 'callout scri
   if [ $utf8 -ne 0 ] ; then
     echo "Testing pcre2grep script callout with UTF-8 features"
     echo "--- Test 1 ---" >testtrygrep
-    $valgrind $vjs $pcre2grep -u '(T)(?C"|$0:$x{a6}$n")' $srcdir/testdata/grepinputv >>testtrygrep
+    $valgrind $vjs $pcre2grep --line-buffered -u '(T)(?C"|$0:$x{a6}$n")' $srcdir/testdata/grepinputv >>testtrygrep
     echo "RC=$?" >>testtrygrep
     echo "--- Test 2 ---" >>testtrygrep
-    $valgrind $vjs $pcre2grep -u '(T)(?C"/bin/echo|$0:$x{a6}$n")' $srcdir/testdata/grepinputv >>testtrygrep
+    $valgrind $vjs $pcre2grep --line-buffered -u '(T)(?C"/bin/echo|$0:$x{a6}$n")' $srcdir/testdata/grepinputv >>testtrygrep
     echo "RC=$?" >>testtrygrep
 
     if [ $nonfork = 1 ] ; then
